// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJKU4AinQlVdAOh02TA_DpnWLMPTLGAs',
    appId: '1:844134705415:web:35df65e15ebdbec118fda2',
    messagingSenderId: '844134705415',
    projectId: 'agrihub-ad0ec',
    authDomain: 'agrihub-ad0ec.firebaseapp.com',
    storageBucket: 'agrihub-ad0ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexq4EV08pbMj7sOF9bEtcNgU3YYsraJs',
    appId: '1:844134705415:android:8b974d6e8acaf83018fda2',
    messagingSenderId: '844134705415',
    projectId: 'agrihub-ad0ec',
    storageBucket: 'agrihub-ad0ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1Af2xhCuplgvk8_MEmBOWDICPMhPwjc',
    appId: '1:844134705415:ios:d78ff208cf2ef95e18fda2',
    messagingSenderId: '844134705415',
    projectId: 'agrihub-ad0ec',
    storageBucket: 'agrihub-ad0ec.appspot.com',
    iosBundleId: 'com.example.agrihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1Af2xhCuplgvk8_MEmBOWDICPMhPwjc',
    appId: '1:844134705415:ios:d78ff208cf2ef95e18fda2',
    messagingSenderId: '844134705415',
    projectId: 'agrihub-ad0ec',
    storageBucket: 'agrihub-ad0ec.appspot.com',
    iosBundleId: 'com.example.agrihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJKU4AinQlVdAOh02TA_DpnWLMPTLGAs',
    appId: '1:844134705415:web:a7d8652ef877083518fda2',
    messagingSenderId: '844134705415',
    projectId: 'agrihub-ad0ec',
    authDomain: 'agrihub-ad0ec.firebaseapp.com',
    storageBucket: 'agrihub-ad0ec.appspot.com',
  );
}
